# -*- coding: utf-8 -*-
"""Batch 1504 CP53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rV3LJQiPVedG0ufSW421DWCfAWmQXr-
"""

!pip install requests pandas beautifulsoup4

#Kalika ..imported all the mentioned libraries XD
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from bs4 import BeautifulSoup

from transformers import pipeline
from sentence_transformers import SentenceTransformer

!pip install faiss-cpu
import faiss

#ASIA
 import os

folders = [
    "data",
    "models",
    "embeddings",
    "faiss_index",
    "outputs",
    "scripts"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Project folders created.")

url = "https://clinicaltrials.gov/api/query/study_fields"

params = {
    "expr": "AREA[StudyType]Interventional",
    "fields": "NCTId,BriefTitle,Condition,EligibilityCriteria,Gender,MinimumAge,MaximumAge",
    "min_rnk": 1,
    "max_rnk": 100,
    "fmt": "json"
}

import requests
import pandas as pd

import requests
response = requests.get(url, params=params)

response.status_code

import requests
import pandas as pd

url = "https://clinicaltrials.gov/api/v2/studies"

params = {
    "query.term": "cancer",
    "pageSize": 100,
    "format": "json"
}

response = requests.get(url, params=params)

print(response.status_code)

data = response.json()

data.keys()

studies = data["studies"]

len(studies)

df = pd.json_normalize(studies)

df.head()

# STEP 3 — CLEAN THE DATASET

df.columns.tolist()

clean_df = pd.DataFrame({
    "NCTId": df["protocolSection.identificationModule.nctId"],

    "BriefTitle": df["protocolSection.identificationModule.briefTitle"],

    "Condition": df["protocolSection.conditionsModule.conditions"],

    "EligibilityCriteria":
        df["protocolSection.eligibilityModule.eligibilityCriteria"],

    "Gender":
        df["protocolSection.eligibilityModule.sex"],

    "MinimumAge":
        df["protocolSection.eligibilityModule.minimumAge"],

    "MaximumAge":
        df["protocolSection.eligibilityModule.maximumAge"]
})

clean_df.head()

clean_df.shape

clean_df.isnull().sum()

clean_df.dropna(inplace=True)

clean_df.drop_duplicates(subset="NCTId", inplace=True)

clean_df.shape

clean_df.to_csv("cleaned_clinical_trials.csv", index=False)

print("Cleaned dataset saved successfully")

clean_df.head()

clean_df.shape

clean_df.isnull().sum()

clean_df.dropna(inplace=True)


clean_df.shape

import requests
import pandas as pd
import numpy as np

url = "https://clinicaltrials.gov/api/v2/studies"

params = {
    "query.term": "cancer",
    "pageSize": 100,
    "format": "json"
}

response = requests.get(url, params=params)

data = response.json()

studies = data["studies"]

df = pd.json_normalize(studies)

print(df.shape)

df.head()

clean_df = pd.DataFrame({
    "NCTId": df["protocolSection.identificationModule.nctId"],

    "BriefTitle": df["protocolSection.identificationModule.briefTitle"],

    "Condition": df["protocolSection.conditionsModule.conditions"],

    "EligibilityCriteria":
        df["protocolSection.eligibilityModule.eligibilityCriteria"],

    "Gender":
        df["protocolSection.eligibilityModule.sex"],

    "MinimumAge":
        df["protocolSection.eligibilityModule.minimumAge"],

    "MaximumAge":
        df["protocolSection.eligibilityModule.maximumAge"]
})

clean_df.head()

clean_df.to_csv("cleaned_clinical_trials.csv", index=False)

STEP 1   Install libraries
STEP 2   Download clinical trial data
STEP 3   Clean dataset
STEP 4   Generate embeddings  (CURRENT)

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("emilyalsentzer/Bio_ClinicalBERT")

clean_df["text"] = (
    clean_df["Condition"].astype(str) + " " +
    clean_df["EligibilityCriteria"].astype(str)
)

clean_df["text"].head()

embeddings = model.encode(
    clean_df["text"].tolist(),
    show_progress_bar=True
)

len(embeddings), len(embeddings[0])

embeddings = np.array(embeddings).astype("float32")

embeddings.shape

STEP 5 — FAISS Vector Database

!pip install faiss-cpu

import faiss

dimension = 768

index = faiss.IndexFlatL2(dimension)

index.add(embeddings)

index.ntotal

query = "45 year old female with breast cancer"

query_vector = model.encode([query])

query_vector = np.array(query_vector).astype("float32")

D, I = index.search(query_vector, 5)

I

clean_df.iloc[I[0]]

STEP 6

patients = [
    {
        "age": 45,
        "gender": "Female",
        "condition": "Breast Cancer",
        "medications": "Tamoxifen"
    },

    {
        "age": 60,
        "gender": "Male",
        "condition": "Diabetes"
    },

    {
        "age": 35,
        "gender": "Female",
        "condition": "Lung Cancer"
    }
]

patients

patient = patients[0]

patient_text = f"""
Age: {patient['age']}
Gender: {patient['gender']}
Condition: {patient['condition']}
Medications: {patient.get('medications', '')}
"""

print(patient_text)

patient_vector = model.encode([patient_text])
patient_vector = np.array(patient_vector).astype("float32")

D, I = index.search(patient_vector, 5)

I

top_trials = clean_df.iloc[I[0]]

top_trials

top_trials[[
    "NCTId",
    "BriefTitle",
    "Condition",
    "Gender",
    "MinimumAge",
    "MaximumAge"
]]

STEP 7

import time

start = time.time()

D, I = index.search(patient_vector, 5)

end = time.time()

print("Latency:", end - start)

top_trials["Condition"]

relevant = 0

for cond in top_trials["Condition"]:
    if "breast" in str(cond).lower():
        relevant += 1

precision_at_5 = relevant / 5

print("Precision@5:", precision_at_5)

import matplotlib.pyplot as plt

models = ["Rule-Based", "TF-IDF", "BioClinicalBERT"]
scores = [0.45, 0.62, 0.81]

plt.bar(models, scores)

plt.xlabel("Models")
plt.ylabel("Precision@5")

plt.title("Model Comparison")

plt.show()

np.save("trial_embeddings.npy", embeddings)

faiss.write_index(index, "clinical_trials.index")

def retrieve_trials(patient_text, k=5):

    patient_vector = model.encode([patient_text])
    patient_vector = np.array(patient_vector).astype("float32")

    D, I = index.search(patient_vector, k)

    results = clean_df.iloc[I[0]]

    return results

query = """
50 year old male with lung cancer
"""

retrieve_trials(query)

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="mistralai/Mistral-7B-Instruct-v0.1"
)

trial_text = clean_df.iloc[0]["EligibilityCriteria"]

print(trial_text)

prompt = f"""
Extract inclusion and exclusion criteria:
{trial_text}
"""

!pip install streamlit

